--------------------------------------------------------
--  File created - Wednesday-July-31-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CLIENT_TRANSACTION
--------------------------------------------------------

  CREATE TABLE "USRTEST"."CLIENT_TRANSACTION" 
   (	"ID" NUMBER, 
	"CLIENT_ID" NUMBER, 
	"TRANSACTION_ID" NUMBER, 
	"CLIENT_SERVICE_TYPE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into USRTEST.CLIENT_TRANSACTION
SET DEFINE OFF;
Insert into USRTEST.CLIENT_TRANSACTION (ID,CLIENT_ID,TRANSACTION_ID,CLIENT_SERVICE_TYPE) values (1,51,210040,'SOAP');
--------------------------------------------------------
--  DDL for Index CLIENT_TRANSACTION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "USRTEST"."CLIENT_TRANSACTION_PK" ON "USRTEST"."CLIENT_TRANSACTION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CLIENT_TRANSACTION
--------------------------------------------------------

  ALTER TABLE "USRTEST"."CLIENT_TRANSACTION" ADD CONSTRAINT "CLIENT_TRANSACTION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "USRTEST"."CLIENT_TRANSACTION" MODIFY ("ID" NOT NULL ENABLE);
